### ISSUE TITLE
embded.compute_diffusion_map 's vectors is stuck into a cycle of positive and negative value 

### ISSUE THREAD

**Issue by YaoMeng94** [satra/mapalign#16]
when I run the "emb, res =embded.compute_diffusion_map(aff, alpha=0.5, return_result = True)", which the "aff" is a 800×800 symmetrical matrix, it return the res with the "vectors" and "emb", if some value of the two array is positive for the first time, and then run the function again it will be negative with the almost same absolute value, I am quit confused about this problem and when I run a lot of matrix it will bring inconsistency, and it will be quite tricky to my work which is about the compute of gradient of human brain functional connectivity. I wish some help can be available for me.

**Comment by YaoMeng94** [comment]
By the way the "aff" matrix is non-negative and sparse, is it the problem arise from the small matrix and I looking fan the answer of stabilizing the result

**Comment by satra** [comment]
@DearBraveJohn - the sign (direction of an eigenvector) of an eigendecomposition is not guaranteed from run to run. depending on your use case, you can flip the direction, or if you are comparing to some template or to another individual or even to the same individual, you can use the alignment algorithms.

**Comment by YaoMeng94** [comment]
thanks for the answer, and specifically how did the alignment algorithms which I have no knowledge about work for this

**Comment by satra** [comment]
here is some info: 

- https://en.wikipedia.org/wiki/Procrustes_transformation
- https://en.wikipedia.org/wiki/Orthogonal_Procrustes_problem

thus the current alignment algorithm makes a few assumptions:
1. the functional modes or components are equivalent across individuals
2. there is a linear transform/mapping between these components.

**Comment by YaoMeng94** [comment]
thanks for the tips, problem already solved.
